<?php
namespace W2w\Laravel\Apie\Controllers;

use Illuminate\Contracts\Routing\UrlGenerator;
use Zend\Diactoros\Response\TextResponse;

/**
 * Renders swagger UI for the openAPI spec generated by Apie.
 */
class SwaggerUiController
{
    private $urlGenerator;

    private $htmlLocation;

    public function __construct(UrlGenerator $urlGenerator, string $htmlLocation)
    {
        $this->urlGenerator = $urlGenerator;
        $this->htmlLocation = $htmlLocation;
    }

    public function __invoke()
    {
        return new TextResponse(str_replace('{{ url }}', $this->urlGenerator->route('apie.docs'), file_get_contents($this->htmlLocation)));
    }
}
