<?php
namespace W2w\Laravel\Apie\Controllers;

use Illuminate\Contracts\Routing\UrlGenerator as LaravelUrlGenerator;
use Laravel\Lumen\Routing\UrlGenerator as LumenUrlGenerator;
use W2w\Laravel\Apie\Exceptions\FileNotFoundException;
use Zend\Diactoros\Response\TextResponse;

/**
 * Renders swagger UI for the openAPI spec generated by Apie.
 */
class SwaggerUiController
{
    private $urlGenerator;

    private $htmlLocation;

    /**
     * @param LaravelUrlGenerator|LumenUrlGenerator $urlGenerator
     * @param string                                $htmlLocation
     */
    public function __construct($urlGenerator, string $htmlLocation)
    {
        $this->urlGenerator = $urlGenerator;
        $this->htmlLocation = $htmlLocation;
    }

    public function __invoke()
    {
        $contents = @file_get_contents($this->htmlLocation);
        if (false === $contents) {
            throw new FileNotFoundException($this->htmlLocation);
        }

        return new TextResponse(
            str_replace('{{ url }}', $this->urlGenerator->route('apie.docs'), $contents),
            200,
            [
                'content-type' => 'text/html'
            ]
        );
    }
}
